/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    AppMain: typeof import('./src/components/AppMain.vue')['default']
    ButtonColorPalette: typeof import('./src/components/ButtonColorPalette.vue')['default']
    ButtonSyncRecords: typeof import('./src/components/ButtonSyncRecords.vue')['default']
    ButtonVersion: typeof import('./src/components/ButtonVersion.vue')['default']
    ButtonWindowClose: typeof import('./src/components/ButtonWindowClose.vue')['default']
    ButtonWindowMaxmise: typeof import('./src/components/ButtonWindowMaxmise.vue')['default']
    ButtonWindowMinimise: typeof import('./src/components/ButtonWindowMinimise.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    IMdiClose: typeof import('~icons/mdi/close')['default']
    IMdiCropSquare: typeof import('~icons/mdi/crop-square')['default']
    IMdiHelp: typeof import('~icons/mdi/help')['default']
    IMdiMinus: typeof import('~icons/mdi/minus')['default']
    IMdiPerson: typeof import('~icons/mdi/person')['default']
    IMdiTranslate: typeof import('~icons/mdi/translate')['default']
    PoolMain: typeof import('./src/components/PoolMain.vue')['default']
    PoolRadio: typeof import('./src/components/PoolRadio.vue')['default']
    PoolRecord: typeof import('./src/components/PoolRecord.vue')['default']
    PoolStatistic: typeof import('./src/components/PoolStatistic.vue')['default']
    SelectorLanguage: typeof import('./src/components/SelectorLanguage.vue')['default']
    SelectorUser: typeof import('./src/components/SelectorUser.vue')['default']
  }
}
