// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {request} from '../models';
import {handler} from '../models';
import {model} from '../models';
import {service} from '../models';

export function GetIcon(arg1:string):Promise<string>;

export function GetLatestRelease():Promise<request.ReleaseInfo>;

export function GetPoolInfo(arg1:number,arg2:number):Promise<handler.PoolInfo>;

export function GetSetting(arg1:string):Promise<string>;

export function GetUserList():Promise<Array<model.User>>;

export function GetVersion():Promise<string>;

export function SelectFilePath():Promise<string>;

export function SetSetting(arg1:string,arg2:string):Promise<void>;

export function SyncRecords(arg1:number,arg2:string):Promise<service.SyncResult>;

export function UpdateTo(arg1:string):Promise<void>;
