// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: proto/GachaData.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GachaData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Units         []*Gacha               `protobuf:"bytes,1,rep,name=Units,proto3" json:"Units,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GachaData) Reset() {
	*x = GachaData{}
	mi := &file_proto_GachaData_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GachaData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GachaData) ProtoMessage() {}

func (x *GachaData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_GachaData_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GachaData.ProtoReflect.Descriptor instead.
func (*GachaData) Descriptor() ([]byte, []int) {
	return file_proto_GachaData_proto_rawDescGZIP(), []int{0}
}

func (x *GachaData) GetUnits() []*Gacha {
	if x != nil {
		return x.Units
	}
	return nil
}

type Gacha struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Type           int64                  `protobuf:"varint,4,opt,name=type,proto3" json:"type,omitempty"`
	RateDesGun     string                 `protobuf:"bytes,22,opt,name=rateDesGun,proto3" json:"rateDesGun,omitempty"`
	RateDesWeapon  string                 `protobuf:"bytes,23,opt,name=rateDesWeapon,proto3" json:"rateDesWeapon,omitempty"`
	WeaponUpItem   string                 `protobuf:"bytes,29,opt,name=weaponUpItem,proto3" json:"weaponUpItem,omitempty"`
	GunUpCharacter string                 `protobuf:"bytes,30,opt,name=gunUpCharacter,proto3" json:"gunUpCharacter,omitempty"`
	OptionalItem   []int64                `protobuf:"varint,36,rep,packed,name=optionalItem,proto3" json:"optionalItem,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Gacha) Reset() {
	*x = Gacha{}
	mi := &file_proto_GachaData_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Gacha) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Gacha) ProtoMessage() {}

func (x *Gacha) ProtoReflect() protoreflect.Message {
	mi := &file_proto_GachaData_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Gacha.ProtoReflect.Descriptor instead.
func (*Gacha) Descriptor() ([]byte, []int) {
	return file_proto_GachaData_proto_rawDescGZIP(), []int{1}
}

func (x *Gacha) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Gacha) GetType() int64 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *Gacha) GetRateDesGun() string {
	if x != nil {
		return x.RateDesGun
	}
	return ""
}

func (x *Gacha) GetRateDesWeapon() string {
	if x != nil {
		return x.RateDesWeapon
	}
	return ""
}

func (x *Gacha) GetWeaponUpItem() string {
	if x != nil {
		return x.WeaponUpItem
	}
	return ""
}

func (x *Gacha) GetGunUpCharacter() string {
	if x != nil {
		return x.GunUpCharacter
	}
	return ""
}

func (x *Gacha) GetOptionalItem() []int64 {
	if x != nil {
		return x.OptionalItem
	}
	return nil
}

var File_proto_GachaData_proto protoreflect.FileDescriptor

const file_proto_GachaData_proto_rawDesc = "" +
	"\n" +
	"\x15proto/GachaData.proto\x12\x02pb\",\n" +
	"\tGachaData\x12\x1f\n" +
	"\x05Units\x18\x01 \x03(\v2\t.pb.GachaR\x05Units\"\xe5\x01\n" +
	"\x05Gacha\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04type\x18\x04 \x01(\x03R\x04type\x12\x1e\n" +
	"\n" +
	"rateDesGun\x18\x16 \x01(\tR\n" +
	"rateDesGun\x12$\n" +
	"\rrateDesWeapon\x18\x17 \x01(\tR\rrateDesWeapon\x12\"\n" +
	"\fweaponUpItem\x18\x1d \x01(\tR\fweaponUpItem\x12&\n" +
	"\x0egunUpCharacter\x18\x1e \x01(\tR\x0egunUpCharacter\x12&\n" +
	"\foptionalItem\x18$ \x03(\x03B\x02\x10\x01R\foptionalItemB\x06Z\x04./pbb\x06proto3"

var (
	file_proto_GachaData_proto_rawDescOnce sync.Once
	file_proto_GachaData_proto_rawDescData []byte
)

func file_proto_GachaData_proto_rawDescGZIP() []byte {
	file_proto_GachaData_proto_rawDescOnce.Do(func() {
		file_proto_GachaData_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_GachaData_proto_rawDesc), len(file_proto_GachaData_proto_rawDesc)))
	})
	return file_proto_GachaData_proto_rawDescData
}

var file_proto_GachaData_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_GachaData_proto_goTypes = []any{
	(*GachaData)(nil), // 0: pb.GachaData
	(*Gacha)(nil),     // 1: pb.Gacha
}
var file_proto_GachaData_proto_depIdxs = []int32{
	1, // 0: pb.GachaData.Units:type_name -> pb.Gacha
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_GachaData_proto_init() }
func file_proto_GachaData_proto_init() {
	if File_proto_GachaData_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_GachaData_proto_rawDesc), len(file_proto_GachaData_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_GachaData_proto_goTypes,
		DependencyIndexes: file_proto_GachaData_proto_depIdxs,
		MessageInfos:      file_proto_GachaData_proto_msgTypes,
	}.Build()
	File_proto_GachaData_proto = out.File
	file_proto_GachaData_proto_goTypes = nil
	file_proto_GachaData_proto_depIdxs = nil
}
