// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: proto/GachaClothesData.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GachaClothesData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Units         []*GachaClothes        `protobuf:"bytes,1,rep,name=Units,proto3" json:"Units,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GachaClothesData) Reset() {
	*x = GachaClothesData{}
	mi := &file_proto_GachaClothesData_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GachaClothesData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GachaClothesData) ProtoMessage() {}

func (x *GachaClothesData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_GachaClothesData_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GachaClothesData.ProtoReflect.Descriptor instead.
func (*GachaClothesData) Descriptor() ([]byte, []int) {
	return file_proto_GachaClothesData_proto_rawDescGZIP(), []int{0}
}

func (x *GachaClothesData) GetUnits() []*GachaClothes {
	if x != nil {
		return x.Units
	}
	return nil
}

type GachaClothes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ClothesUpItem string                 `protobuf:"bytes,7,opt,name=clothesUpItem,proto3" json:"clothesUpItem,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GachaClothes) Reset() {
	*x = GachaClothes{}
	mi := &file_proto_GachaClothesData_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GachaClothes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GachaClothes) ProtoMessage() {}

func (x *GachaClothes) ProtoReflect() protoreflect.Message {
	mi := &file_proto_GachaClothesData_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GachaClothes.ProtoReflect.Descriptor instead.
func (*GachaClothes) Descriptor() ([]byte, []int) {
	return file_proto_GachaClothesData_proto_rawDescGZIP(), []int{1}
}

func (x *GachaClothes) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GachaClothes) GetClothesUpItem() string {
	if x != nil {
		return x.ClothesUpItem
	}
	return ""
}

var File_proto_GachaClothesData_proto protoreflect.FileDescriptor

const file_proto_GachaClothesData_proto_rawDesc = "" +
	"\n" +
	"\x1cproto/GachaClothesData.proto\x12\x02pb\":\n" +
	"\x10GachaClothesData\x12&\n" +
	"\x05Units\x18\x01 \x03(\v2\x10.pb.GachaClothesR\x05Units\"D\n" +
	"\fGachaClothes\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12$\n" +
	"\rclothesUpItem\x18\a \x01(\tR\rclothesUpItemB\x06Z\x04./pbb\x06proto3"

var (
	file_proto_GachaClothesData_proto_rawDescOnce sync.Once
	file_proto_GachaClothesData_proto_rawDescData []byte
)

func file_proto_GachaClothesData_proto_rawDescGZIP() []byte {
	file_proto_GachaClothesData_proto_rawDescOnce.Do(func() {
		file_proto_GachaClothesData_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_GachaClothesData_proto_rawDesc), len(file_proto_GachaClothesData_proto_rawDesc)))
	})
	return file_proto_GachaClothesData_proto_rawDescData
}

var file_proto_GachaClothesData_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_GachaClothesData_proto_goTypes = []any{
	(*GachaClothesData)(nil), // 0: pb.GachaClothesData
	(*GachaClothes)(nil),     // 1: pb.GachaClothes
}
var file_proto_GachaClothesData_proto_depIdxs = []int32{
	1, // 0: pb.GachaClothesData.Units:type_name -> pb.GachaClothes
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_GachaClothesData_proto_init() }
func file_proto_GachaClothesData_proto_init() {
	if File_proto_GachaClothesData_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_GachaClothesData_proto_rawDesc), len(file_proto_GachaClothesData_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_GachaClothesData_proto_goTypes,
		DependencyIndexes: file_proto_GachaClothesData_proto_depIdxs,
		MessageInfos:      file_proto_GachaClothesData_proto_msgTypes,
	}.Build()
	File_proto_GachaClothesData_proto = out.File
	file_proto_GachaClothesData_proto_goTypes = nil
	file_proto_GachaClothesData_proto_depIdxs = nil
}
