// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: proto/ItemData.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ItemData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Units         []*Item                `protobuf:"bytes,1,rep,name=Units,proto3" json:"Units,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemData) Reset() {
	*x = ItemData{}
	mi := &file_proto_ItemData_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemData) ProtoMessage() {}

func (x *ItemData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ItemData_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemData.ProtoReflect.Descriptor instead.
func (*ItemData) Descriptor() ([]byte, []int) {
	return file_proto_ItemData_proto_rawDescGZIP(), []int{0}
}

func (x *ItemData) GetUnits() []*Item {
	if x != nil {
		return x.Units
	}
	return nil
}

type Item struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name  *LanguageStringData    `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// LanguageStringData introduction = 3;
	// repeated string description = 4;
	Type int64 `protobuf:"varint,5,opt,name=type,proto3" json:"type,omitempty"`
	// string icon = 6;
	Rank          int64 `protobuf:"varint,8,opt,name=rank,proto3" json:"rank,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Item) Reset() {
	*x = Item{}
	mi := &file_proto_ItemData_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ItemData_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_proto_ItemData_proto_rawDescGZIP(), []int{1}
}

func (x *Item) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Item) GetName() *LanguageStringData {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *Item) GetType() int64 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *Item) GetRank() int64 {
	if x != nil {
		return x.Rank
	}
	return 0
}

var File_proto_ItemData_proto protoreflect.FileDescriptor

const file_proto_ItemData_proto_rawDesc = "" +
	"\n" +
	"\x14proto/ItemData.proto\x12\x02pb\x1a\x1eproto/LanguageStringData.proto\"*\n" +
	"\bItemData\x12\x1e\n" +
	"\x05Units\x18\x01 \x03(\v2\b.pb.ItemR\x05Units\"j\n" +
	"\x04Item\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12*\n" +
	"\x04name\x18\x02 \x01(\v2\x16.pb.LanguageStringDataR\x04name\x12\x12\n" +
	"\x04type\x18\x05 \x01(\x03R\x04type\x12\x12\n" +
	"\x04rank\x18\b \x01(\x03R\x04rankB\x06Z\x04./pbb\x06proto3"

var (
	file_proto_ItemData_proto_rawDescOnce sync.Once
	file_proto_ItemData_proto_rawDescData []byte
)

func file_proto_ItemData_proto_rawDescGZIP() []byte {
	file_proto_ItemData_proto_rawDescOnce.Do(func() {
		file_proto_ItemData_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_ItemData_proto_rawDesc), len(file_proto_ItemData_proto_rawDesc)))
	})
	return file_proto_ItemData_proto_rawDescData
}

var file_proto_ItemData_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_ItemData_proto_goTypes = []any{
	(*ItemData)(nil),           // 0: pb.ItemData
	(*Item)(nil),               // 1: pb.Item
	(*LanguageStringData)(nil), // 2: pb.LanguageStringData
}
var file_proto_ItemData_proto_depIdxs = []int32{
	1, // 0: pb.ItemData.Units:type_name -> pb.Item
	2, // 1: pb.Item.name:type_name -> pb.LanguageStringData
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_ItemData_proto_init() }
func file_proto_ItemData_proto_init() {
	if File_proto_ItemData_proto != nil {
		return
	}
	file_proto_LanguageStringData_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_ItemData_proto_rawDesc), len(file_proto_ItemData_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_ItemData_proto_goTypes,
		DependencyIndexes: file_proto_ItemData_proto_depIdxs,
		MessageInfos:      file_proto_ItemData_proto_msgTypes,
	}.Build()
	File_proto_ItemData_proto = out.File
	file_proto_ItemData_proto_goTypes = nil
	file_proto_ItemData_proto_depIdxs = nil
}
